- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/admin_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/configs_controller.rb
- app/controllers/landmarks_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
- app/models/role.rb
- app/models/user.rb
- app/views/configs/index.html.haml
- app/views/users/index.html.haml
- config/application.rb
- config/initializers/rolify.rb
- config/routes.rb
- db/migrate/20170208161600_rolify_create_roles.rb
- db/schema.rb
- spec/controllers/configs_controller_spec.rb
- spec/controllers/landmarks_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/roles.rb
- spec/factories/users.rb
- spec/models/role_spec.rb
- spec/models/user_spec.rb
Create admin role and restrict the admin functionality to the admin users.
> Create Admin Role

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/places_controller.rb
- app/controllers/api/v1/registrations_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- app/controllers/application_controller.rb
- db/migrate/20170209155748_add_first_and_last_name_to_users.rb
- db/schema.rb
- spec/controllers/api/v1/registrations_controller_spec.rb
- spec/controllers/api/v1/sessions_controller_spec.rb
- spec/factories/users.rb
Additional Auth functionality--first name, last name, password confirmation
> Devise auth

- app/controllers/admin/accommodations_controller.rb
- app/controllers/admin/eligibilities_controller.rb
- app/models/accommodation.rb
- app/models/concerns/eligibility_accommodation_helper.rb
- app/models/eligibility.rb
- app/views/admin/accommodations/index.html.haml
- app/views/admin/configs/index.html.haml
- app/views/admin/eligibilities/index.html.haml
- app/views/admin/landmarks/index.html.haml
- config/routes.rb
- db/migrate/20170213160751_create_eligibilities.rb
- db/migrate/20170213160846_create_accommodations.rb
- db/schema.rb
- lib/tasks/sample.rake
- spec/controllers/admin/accommodations_controller_spec.rb
- spec/controllers/admin/eligibilities_controller_spec.rb
- spec/factories/accommodations.rb
- spec/factories/eligibilities.rb
- spec/models/accommodation_spec.rb
- spec/models/eligibility_spec.rb
Added Admin interfaces for managing eligibilities and accommodations.
> Edit Configs, Accommodations, and Eligibilities

- Gemfile
- Gemfile.lock
- app/controllers/admin/services_controller.rb
- app/controllers/api/v1/trips_controller.rb
- app/models/itinerary.rb
- app/models/trip_planner.rb
- app/services/otp_ambassador.rb
- config/initializers/carrierwave.rb
- spec/controllers/api/v1/trips_controller_spec.rb
- spec/factories/itineraries.rb
- spec/models/itinerary_spec.rb
- spec/models/trip_planner_spec.rb
- Populate Paratransit itinerary transit_time on plan call
- Build spec for TripPlanner and TripsController, stubbing out external objects
- Install Fog gem to allow Carrierwave uploading to AWS
- Improve comments in ServicesController
> Response to Code Review 2/27/17

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/places_controller.rb
- app/controllers/api/v1/trips_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/itinerary.rb
- app/models/services/service.rb
- app/serializers/api/v1/itinerary_serializer.rb
- app/serializers/api/v1/trip_serializer.rb
- app/serializers/api_v1/trip_serializer.rb
- app/services/otp_ambassador.rb
- config/routes.rb
- spec/controllers/api/v1/places_controller_spec.rb
- spec/controllers/api/v1/trips_controller_spec.rb
You can plan trips and see basic transit/paratransit results via the new UI.
> Api v1 setup

- app/controllers/api/v1/trips_controller.rb
- app/models/trip_planner.rb
- db/seeds.rb
- lib/tasks/sample.rake
- spec/controllers/admin/configs_controller_spec.rb
- spec/controllers/api/v1/places_controller_spec.rb
- spec/models/trip_planner_spec.rb
- spec/spec_helper.rb
Refactor TripPlanner and API Trips Controller using TRIP_TYPES list of symbols rather than mode code strings.
> Trip types

- Gemfile
- Gemfile.lock
- app/controllers/admin/services_controller.rb
- app/models/services/paratransit.rb
- app/models/services/service.rb
- app/models/services/transit.rb
- app/models/trip_planner.rb
- app/services/otp_ambassador.rb
- app/services/otp_service.rb
- spec/controllers/admin/configs_controller_spec.rb
- spec/factories/configs.rb
- spec/models/service_spec.rb
- spec/models/trip_planner_spec.rb
Implement asynchronous HTTP calls to OTP
ALSO: 
- fix some bugs in the service admin pages
- refactor some methods from Service model to subclasses
- update spec as needed
> OTP Asynchronous Calls

- app/models/concerns/eligibility_accommodation_helper.rb
- app/models/trip_planner.rb
- app/services/http_request_bundler.rb
- app/services/otp_ambassador.rb
- app/services/otp_service.rb
- app/services/tff_ambassador.rb
- app/services/tff_service.rb
- spec/controllers/api/v1/trips_controller_spec.rb
- spec/factories/configs.rb
- spec/models/trip_planner_spec.rb
Implement asynchronous bundling of OTP and TFF api calls.
> Async api calls

- app/models/concerns/scope_helper.rb
- app/models/region.rb
- app/models/schedule.rb
- app/models/services/paratransit.rb
- app/models/services/service.rb
- app/models/services/taxi.rb
- app/models/services/transit.rb
- app/models/trip.rb
- app/services/benchmark_helper.rb
- spec/models/service_spec.rb
Refactor all of the service available_for logic into Rails scopes rather than pure ruby methods.
> Service scopes

- app/controllers/api/api_controller.rb
- app/controllers/concerns/api_error_catcher.rb
- app/serializers/api/v1/itinerary_serializer.rb
- app/services/schedule_helper.rb
Reverts camsys/oneclick-core#57
> Revert "Serializers plan call 500 errors"

- app/controllers/admin/users_controller.rb
- app/views/admin/feedbacks/show.html.haml
- app/views/admin/services/show.html.haml
- app/views/admin/users/_edit_user.haml
- app/views/admin/users/edit.html.haml
- app/views/admin/users/index.html.haml
- app/views/layouts/application.html.erb
- config/routes.rb
- lib/tasks/sample.rake
- spec/controllers/admin/users_controller_spec.rb
- spec/factories/users.rb
You can also view and edit your own profile.
> You can Edit Staff Members

- app/controllers/api/v1/feedbacks_controller.rb
- app/controllers/api/v2/feedbacks_controller.rb
- app/models/feedback.rb
- app/views/admin/feedbacks/_feedback.html.haml
- app/views/admin/feedbacks/_feedbacks_table.html.haml
- config/routes.rb
- db/migrate/20170615143154_add_email_and_phone_number_to_feedback.rb
- db/schema.rb
- spec/controllers/api/v2/feedbacks_controller_spec.rb
- spec/factories/feedbacks.rb
- spec/models/feedback_spec.rb
Allows anonymous feedbacks, and adds email and phone fields to feedbacks table.
> Feedbacks Improvements

- lib/tasks/import.rake
You can do this now and pull in accs, eligs, and purps from Oneclick Legacy
rake import:all['http://localhost:3001','THISISARANDOMSTRING']
> Import accs, eligs, and purps

- app/controllers/api/api_controller.rb
- app/controllers/api/v2/agencies_controller.rb
- app/controllers/api/v2/trips_controller.rb
- app/models/accommodation.rb
- app/models/concerns/characteristics_helper.rb
- app/models/eligibility.rb
- app/models/multiday_trip_planner.rb
- app/models/purpose.rb
- app/models/service.rb
- app/models/trip_planner.rb
- app/models/user.rb
- app/serializers/api/v2/itinerary_serializer.rb
- app/serializers/api/v2/trip_serializer.rb
- config/routes.rb
- spec/factories/multiday_trip_planners.rb
- spec/models/multiday_trip_planner_spec.rb
- spec/models/trip_planner_spec.rb
- Allows planning of multiday trips
- Moves Trip Plan call to API V2
> Plan medical trips

- app/models/concerns/commentable.rb
- app/models/concerns/contactable.rb
- app/models/user.rb
- db/migrate/20170719153915_modify_agency_reference_to_services.rb
- db/schema.rb
- lib/tasks/helpers/import_task_helpers.rb
- lib/tasks/import.rake
- Create import task helpers module
- Import registered and guest users
- Begin building clean_up task
- Fix issue with Agencies table preventing deletion of agencies
- Make modifications to Agencies import
> Import users

- .gitignore
- app/models/concerns/contactable.rb
- config/database.yml
- lib/tasks/helpers/import_task_helpers.rb
- lib/tasks/import.rake
> Import services

- app/models/concerns/contactable.rb
- app/models/place.rb
- app/models/waypoint.rb
- lib/tasks/helpers/import_task_helpers.rb
- lib/tasks/import.rake
- Imports trips and itineraries
- Also allows underscores in email addresses (for CPTA users import)
- Also builds point geoms before save on all Place models.
> Import trips

- app/controllers/api/v2/users_controller.rb
- app/models/concerns/characteristics_helper.rb
- app/models/trip_planner.rb
- app/models/user.rb
- app/serializers/api/v2/user_serializer.rb
- spec/controllers/api/v1/trips_controller_spec.rb
- spec/controllers/api/v2/users_controller_spec.rb
- spec/models/user_spec.rb
Done for api/v2 but will probably work for api/v1 as well.
> Update the password via the Update Profile Call

- app/controllers/api/v2/refernet/services_controller.rb
- app/services/external_api_ambassadors/otp_services.rb
- config/routes.rb
http://localhost:3000/api/v2/oneclick_refernet/services?sub_sub_category=At%20Risk/Homeless%20Housing%20Related%20Assistance%20Programs%20*%20Veterans&lat=28.472&lng=-81.281
> Return Drive and Transit Time with Refernet Service Call

- app/controllers/admin/alerts_controller.rb
- app/models/alert.rb
- app/models/user.rb
- app/models/user_alert.rb
- config/routes.rb
- spec/factories/alerts.rb
Documented here: https://github.com/camsys/oneclick-core/wiki/API-V2#alerts
> Alerts API Call

- app/controllers/api/v2/services_controller.rb
- app/serializers/api/v2/service_serializer.rb
- config/routes.rb
- spec/controllers/api/v2/agencies_controller_spec.rb
- spec/controllers/api/v2/services_controller_spec.rb
Create a API V2 services controller and index action for returning all services, optionally filtered by type.
> Api services controller

- app/mailers/user_mailer.rb
- app/models/concerns/role_helper.rb
- app/models/feedback.rb
- app/views/admin/feedbacks/_feedbacks_table.html.haml
- app/views/user_mailer/admin_feedback_reminder.html.haml
- app/views/user_mailer/transportation_agency_feedback_reminder.html.haml
- lib/tasks/scheduled.rake
Feedback Reminders after 5 days of not being acknowledged.
> Finish Feedback Reminders

- Gemfile
- db/schema.rb
Fix Migrations and Update GemFile Reference for Refernet to Master
> Merge Proximity into Master

- app/models/landmark.rb
OCC-233 - Errors generated when uploading a .csv file to the landmarks page are now more descriptive.
> Landmark error message

- app/models/landmark.rb
- app/views/admin/landmarks/_landmark_form.html.haml
- config/initializers/version.rb
Reverts camsys/oneclick-core#156
> Revert "Landmark error message"

- app/models/landmark.rb
> Fixed csv confirmation msg to display correct number of lines added

- .gitignore
- app/controllers/admin/users_controller.rb
- app/controllers/concerns/admin_helpers.rb
- app/models/concerns/role_helper.rb
- app/views/admin/users/_new_traveler.html.haml
- app/views/admin/users/_traveler_form.html.haml
- app/views/admin/users/_user_form.html.haml
- app/views/admin/users/all.html.haml
- app/views/admin/users/edit.html.haml
- app/views/admin/users/staff.html.haml
- app/views/admin/users/travelers.html.haml
- config/routes.rb
- spec/controllers/admin/users_controller_spec.rb
> Add Travelers and Staff Pages

- app/controllers/api/v1/places_controller.rb
- lib/tasks/ecolane.rake
Add code to prevent One Click from returning city-less Places and syncing city-less POIs
Has an associated [FMR Pull Request](https://github.com/camsys/applymyride/pull/31)
> PAMF-696 ecolane missing city

- app/controllers/api/api_controller.rb
- app/controllers/api/v2/trips_controller.rb
- app/controllers/api/v2/users_controller.rb
- app/serializers/admin/trips_report_csv_writer.rb
Add additional columns to reporting.
- there is some front end code in the OneClick-ionic associated with this. See linked [pull request](https://github.com/camsys/oneclick-ionic-ui/pull/7)
- this branch is based on the `lydia_translation_engine` branch and will need to figure out which branch to merge this into!
> Occ 577/additional 211 reporting

- .gitignore
- app/assets/javascripts/admin/datatables.js
- app/controllers/admin/purposes_travel_patterns_controller.rb
- app/models/agency.rb
- app/models/purpose.rb
- app/views/admin/purposes_travel_patterns/_form.html.haml
- app/views/admin/purposes_travel_patterns/edit.html.haml
- app/views/admin/purposes_travel_patterns/index.html.haml
- app/views/admin/purposes_travel_patterns/new.html.haml
- app/views/admin/purposes_travel_patterns/show.html.haml
- app/views/layouts/_modal.html.haml
- app/views/shared/_select_agency.html.haml
- config/routes.rb
- db/migrate/20220424222311_add_fields_to_purposes.rb
- db/schema.rb
> Adding new Trip Purposes pages for travel patterns

- app/assets/javascripts/admin/datatables.js
- app/controllers/admin/funding_sources_controller.rb
- app/models/ability.rb
- app/models/agency.rb
- app/models/funding_source.rb
- app/views/admin/funding_sources/_form.html.haml
- app/views/admin/funding_sources/edit.html.haml
- app/views/admin/funding_sources/index.html.haml
- app/views/admin/funding_sources/new.html.haml
- app/views/admin/funding_sources/show.html.haml
- config/routes.rb
- db/migrate/20220502154926_create_funding_sources.rb
- db/schema.rb
- spec/factories/funding_sources.rb
> Funding Sources

- app/assets/javascripts/admin/autocomplete.js
- app/assets/javascripts/admin/forms.js
- app/controllers/admin/services_controller.rb
- app/views/admin/services/_paratransit_booking.html.haml
- app/views/admin/services/_travel_patterns.html.haml
> Changed FormHandler to allow callbacks for autocomplete fields

- app/assets/stylesheets/admin/_travel_pattern_forms.scss
- app/controllers/admin/admin_controller.rb
- app/controllers/admin/booking_windows_controller.rb
- app/controllers/admin/funding_sources_controller.rb
- app/controllers/admin/landmark_sets_controller.rb
- app/controllers/admin/purposes_travel_patterns_controller.rb
- app/controllers/admin/service_schedules_controller.rb
- app/controllers/admin/travel_patterns_controller.rb
- app/models/service_schedule.rb
- app/models/service_schedule_type.rb
- app/models/service_sub_schedule.rb
- app/models/travel_pattern.rb
- app/models/travel_pattern_service_schedule.rb
- app/views/admin/landmark_sets/edit.html.haml
- app/views/admin/landmark_sets/index.html.haml
- app/views/admin/landmark_sets/new.html.haml
- app/views/admin/service_schedules/_service_sub_schedule_form.html.haml
- app/views/admin/service_schedules/index.html.haml
- app/views/admin/travel_patterns/_travel_pattern_form.html.haml
- app/views/admin/travel_patterns/_travel_pattern_funding_sources_form.html.haml
- app/views/admin/travel_patterns/_travel_pattern_purposes_form.html.haml
- app/views/admin/travel_patterns/_travel_pattern_service_schedules_form.html.haml
- db/migrate/20220713133533_add_override_flag_to_travel_pattern_service_schedules.rb
- db/schema.rb
- lib/tasks/sample.rake
OCC-785
OCC-799
OCC-792
OCC-791
OCC-790
> Various fixes and improvements

- app/assets/stylesheets/admin/_auto-complete-fields.scss
- app/controllers/admin/configs_controller.rb
- app/controllers/api/v2/travel_patterns_controller.rb
- app/controllers/api/v2/trips_controller.rb
- app/models/booking_window.rb
- app/models/landmark.rb
- app/models/od_zone.rb
- app/models/region.rb
- app/models/service_schedule.rb
- app/models/service_sub_schedule.rb
- app/models/travel_pattern.rb
- app/views/admin/booking_windows/_form.html.haml
- app/views/admin/configs/_miscellaneous.html.haml
- app/views/admin/travel_patterns/_travel_pattern_form.html.haml
- app/views/admin/travel_patterns/index.html.haml
- config/routes.rb
- db/seeds.rb
- lib/tasks/ecolane.rake
- lib/tasks/qa.rake
- spec/controllers/api/v2/travel_patterns_controller.rb
- spec/controllers/api/v2/trips_controller_spec.rb
- spec/factories/booking_windows.rb
- spec/factories/od_zones.rb
- spec/factories/service_schedule_types.rb
- spec/factories/service_schedules.rb
- spec/factories/service_sub_schedules.rb
- spec/factories/travel_pattern_purposes.rb
- spec/factories/travel_pattern_service_schedules.rb
- spec/factories/travel_patterns.rb
- spec/factories/traveler_transit_agencies.rb
OCC-812
OCC-809
OCC-808
OCC-807
OCC-806
OCC-803
OCC-802
> Added Route for Trips to validate using Travel Patterns

- app/controllers/admin/reports_controller.rb
- app/models/concerns/csv_writable.rb
- app/serializers/csv_writer.rb
- app/views/admin/reports/_requests_table_download_options.html.haml
- app/views/admin/reports/_trips_table_download_options.html.haml
Improve performance of trips report in regards to the "Only Show Trips Created in 1Click" filter, and limiting records returned to 50000.
> Occ 816 fmr 174

- app/views/admin/reports/_requests_table_download_options.html.haml
- app/views/admin/reports/_trips_table_download_options.html.haml
Editing for an exclamation point to make sure the environment is setup right
> Occ 1183 2

- app/models/place.rb
- app/services/external_api_ambassadors/ecolane_ambassador.rb
- config/initializers/version.rb
* FMRPA-220 | Making changes to ensure nil is handled gracefully for valid_from and valid_until dates
* v1.18.19-rc.1
* v1.18.19-rc.2
* Fixing the merge issues, for real this time.
---------
> merge from QA (#365)
